layout_spectrum: 0.8253869
typography_spectrum: 0.3639717
color:
  saturation: 0.4613222
  lightness: 0.6114018
  brandStrength: 0.01106253
  rhythmicContrast: 0.8401312
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Rolf Bosscha
